
public interface LoadingScreenConstants {
    public final static String LOADING_SCREEN_FILTER ="QUIZZY_LOADING_SCREEN",MSG_LOADING_TEXT ="LOADING_TEXT",MSG_CENTER_TEXT ="CENTER_TEXT",MSG_FOOTER_TEXT ="FOOTER_TEXT",MSG_VISIBLE_LOADING_TEXT ="VISIBLE_LOADING_TEXT",MSG_INVISIBLE_LOADING_TEXT ="INVISIBLE_LOADING_TEXT",MSG_VISIBLE_CENTER_TEXT ="VISIBLE_CENTER_TEXT",MSG_INVISIBLE_CENTER_TEXT ="INVISIBLE_CENTER_TEXT",MSG_VISIBLE_FOOTER_TEXT ="VISIBLE_FOOTER_TEXT",MSG_INVISIBLE_FOOTER_TEXT ="INVISIBLE_FOOTER_TEXT",MSG_VISIBLE_GBUTTON ="VISIBLE_GBUTTON",MSG_INVISIBLE_GBUTTON ="INVISIBLE_GBUTTON",STARTING_BUNDLE_STRING ="BUNDLE_STRING";
}
